
version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - pip3 install -r sparkscripts/csv_to_parquet.requirements
  build:
    commands:
      - echo Entered the build phase...
      - export PYSPARK_PYTHON=python3.7
      - python3 -m unittest discover -s tests
      - echo Build started on `date`
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'