#!/bin/bash
if [[ ! -d /home/hadoop/sparkscripts ]]
then
    mkdir /home/hadoop/sparkscripts
fi

if [[ ! -d /home/hadoop/scripts ]]
then
    mkdir /home/hadoop/scripts
fi

if [[ ! -d /home/hadoop/tests ]]
then
    mkdir /home/hadoop/tests
fi